name: Build C# Project 22222

on:
  workflow_dispatch:  # 仅手动触发

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 获取代码

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1  # 安装 MSBuild

      - name: Restore NuGet packages
        run: nuget restore JD_Get.sln  # 还原 NuGet 依赖

      - name: Build project
        run: msbuild JD_Get.sln /p:Configuration=Release /p:Platform="Any CPU"  # 确保 Release 版本被生成

      - name: Debug Check Compilation Output
        run: Get-ChildItem -Path JD_Get\bin\ -Recurse  # 确保 bin 目录下有内容

      - name: Debug: Find EXE Location
        run: Get-ChildItem -Path JD_Get\ -Filter "*.exe" -Recurse  # 确保 EXE 生成了

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: JD_Get_Build
          path: JD_Get/bin/Release/  # 确保路径正确
