name: Build C# Project 22222

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore JD_Get.sln

      - name: Build project
        run: msbuild JD_Get.sln /p:Configuration=Release /p:Platform="Any CPU" -verbosity:diagnostic

      - name: Check all directories after build
        run: Get-ChildItem -Path . -Recurse

      - name: Ensure output directory exists
        run: |
          if (!(Test-Path "JD_Get/bin/Release/")) { 
            Write-Error "Error: Build output directory does not exist!"
            exit 1 
          }

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: JD_Get_Build
          path: JD_Get/bin/Release/
