name: Build C# Project 22222

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # 使用最新版本的 Windows 环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 检出代码仓库

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1  # 设置 MSBuild 环境

      - name: Restore NuGet packages
        run: |
          nuget restore JD_Get.sln  # 恢复 NuGet 包
          if ($LASTEXITCODE -ne 0) {  # 检查 NuGet 还原是否成功
            Write-Error "Error: NuGet restore failed!"  # 如果失败，输出错误信息
            exit 1  # 退出并标记失败
          }

      - name: Build project with MSBuild
        run: |
          msbuild JD_Get.sln /p:Configuration=Release /p:Platform="Any CPU" -verbosity:detailed  # 使用 MSBuild 编译项目，设置为 Release 配置
          if ($LASTEXITCODE -ne 0) {  # 检查 MSBuild 是否成功
            Write-Error "Error: MSBuild failed!"  # 如果失败，输出错误信息
            exit 1  # 退出并标记失败
          }

      - name: List all directories after build (Debugging)
        run: |
          Get-ChildItem -Path . -Recurse | Where-Object { $_.PSIsContainer }  # 列出所有目录，用于调试，检查目录结构

      - name: Verify output directory exists
        run: |
          # 检查 'JD_Get/bin/Release/' 是否存在，如果没有，输出错误并终止
          if (!(Test-Path "JD_Get/bin/Release/")) {  
            Write-Error "Error: Build output directory does not exist!"  # 如果目录不存在，输出错误信息
            exit 1  # 退出并标记失败
          }

      - name: Publish artifact
        uses: actions/upload-artifact@v4  # 上传构建产物
        with:
          name: JD_Get_Build  # 设置上传的产物名称
          path: JD_Get/bin/Release/  # 上传构建结果目录
