name: Build C# Project

on:
  push:
    branches:
      - main   # 或者你选择的其他分支
  pull_request:
    branches:
      - main   # 或者你选择的其他分支

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'  # 选择你的 .NET 版本，可以根据需要调整

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish --configuration Release --output ./output

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: JD_Get-build
        path: ./output
