name: Build and Test



on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore NuGet Packages
        run: nuget restore JD_Get.sln

      - name: Build Project
        run: msbuild JD_Get.sln /p:Configuration=Release /p:Platform="Any CPU"
